# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tog < Formula
  desc "Tog CLI"
  homepage "https://github.com/escaletech/tog-cli"
  version "0.3.2"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/escaletech/tog-cli/releases/download/v0.3.2/tog_0.3.2_macOS_amd64.tar.gz"
      sha256 "07f5705c44916a4357e2fceb8259a6a87e96568ee4c43d41e5a5c84d529a093b"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/escaletech/tog-cli/releases/download/v0.3.2/tog_0.3.2_linux_amd64.tar.gz"
      sha256 "52f05b4789ba71b4e6bc1ccb74e011ce081d048502fa5e1b36a2f78e7a6e7462"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/escaletech/tog-cli/releases/download/v0.3.2/tog_0.3.2_linux_arm64.tar.gz"
      sha256 "2b3b8ac14eb26fb96a343c503c8d2eba17fa3a56a373c68b37af6e49a0bc0b68"
    end
  end

  def install
    bin.install "tog"
  end

  test do
    help_text = shell_output("#{bin}/tog --help")
    assert_includes help_text, "Usage:"
  end
end
